### ISSUE TITLE
[Question] Factory Style

### ISSUE THREAD

**Issue by guilhermedecampo** [abhiaiyer91/ZenActions#1]
Hi @abhiaiyer91 thanks for this package and the concept! 
Really great take off the business logic to the views and mixins seems to be a perfect match.

If you don't mind I fork your package and rewrote in a factory way. 
Since in the README you say you like more the class way of React I suppose it's the same for javascript in general so I didn't submit a PR.

Also I see that you didn't add any license, so I'm ask your permission to use and modify after doing it haha =)

Thanks,

**Comment by abhiaiyer91** [comment]
@guilhermedecampo Thats cool! 

Let me add a license now :)

Could I see your work? Maybe its the right way to go.

**Comment by abhiaiyer91** [comment]
@guilhermedecampo Lets do factory style. Send me a PR

**Comment by guilhermedecampo** [comment]
Yoohoo! I'll do it =)
